# Generated by Django 4.2 on 2025-02-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spaceuserequest',
            new_name='events_spac_state_d4c31f_idx',
            old_fields=('state', 'changed'),
        ),
    ]
